import type { Metadata } from "next";
import { Inter, Open_Sans, Oswald } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const opensans = Open_Sans({
  subsets: ["latin"],
  variable: "--font-opensans",
});

const oswald = Oswald({
  subsets: ["latin"],
  variable: "--font-oswald",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${opensans.variable} ${oswald.variable}`} 
      >
        {children}
      </body>
    </html>
  );
}
